FROM python:3.8-slim

RUN apt-get update && \
    apt-get install -y ffmpeg git libsm6 libxext6 libxrender-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

CMD ["/bin/bash"]